"""Migrate model task

Revision ID: 393690fe7dae
Revises: dad911e9ee01
Create Date: 2020-08-07 14:46:56.324797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393690fe7dae'
down_revision = 'dad911e9ee01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
